name: Deploy to EC2 (stage)

on:
  push:
    branches:
      - stage



jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Setup pnpm
        uses: pnpm/action-setup@v4


      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Build Frontend
        env:
          NEXT_PUBLIC_API_URL: https://api.autospace.space
          BASE_URL: https://api.autospace.space 
        run: |
          cd nextjs-autospace
          pnpm install
          pnpm build   

      - name: Prepare frontend folder on EC2
        run: |
          ssh -i ~/.ssh/id_ed25519 ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} "mkdir -p ~/frontend"
    
      - name: Copy frontend build to EC2
        run: |
          scp -i ~/.ssh/id_ed25519 -r nextjs-autospace/.next ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:~/frontend/
          scp -i ~/.ssh/id_ed25519 -r nextjs-autospace/public ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:~/frontend/
          scp -i ~/.ssh/id_ed25519 nextjs-autospace/package.json ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:~/frontend/
          scp -i ~/.ssh/id_ed25519 nextjs-autospace/pnpm-lock.yaml ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:~/frontend/


      - name: Deploy to EC2
        run: |
          ssh ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
          set -e

          echo "Deploying API Gateway..."
          cd ~/autospace
          git fetch origin
          git reset --hard origin/stage
         

          cd nodejs-autospace/api-gateway
          pnpm install --prod --ignore-scripts
          NODE_ENV=stage pm2 restart api-gateway || NODE_ENV=stage pm2 start dist/index.js --name api-gateway

          echo "Deploying Auth Service..."
          cd ~/auth-service/autospace
          git fetch origin
          git reset --hard origin/stage
        

          cd nodejs-autospace/auth-service
          pnpm install --prod --ignore-scripts
          NODE_ENV=stage pm2 restart auth-service || NODE_ENV=stage pm2 start dist/server.js --name auth-service

          echo "Deploying Resource Service..."
          cd ~/resource-service/autospace
          git fetch origin
          git reset --hard origin/stage
         

          cd nodejs-autospace/resource-service
          pnpm install --prod --ignore-scripts
          NODE_ENV=stage pm2 restart resource-service || NODE_ENV=stage pm2 start dist/server.js --name resource-service

          echo "Deploying Booking Service..."
          cd ~/booking-service/nodejs-autospace/booking-service

          git fetch origin
          git reset --hard origin/stage
        
          pnpm install --prod --ignore-scripts
          NODE_ENV=stage pm2 restart booking-service || NODE_ENV=stage pm2 start dist/server.js --name booking-service

          echo "Deploying Frontend..."
          cd ~/frontend

          pnpm install --prod --ignore-scripts

          pm2 restart frontend || pm2 start "pnpm start" --name frontend

          pm2 save
          EOF
